### ISSUE TITLE
Content and interited layouts cause multiplication of content

### ISSUE THREAD

**Issue by white-gecko** [white-gecko/jekyll-rdf#77]
I've put the MWE in https://github.com/white-gecko/MWE-jekyll-rdf-layouts-content-issue

even simpler:
There are two layouts `_layouts/default.html` and `_layouts/document.html`

default:

    {{ content }}

document:

    PageRDF (this URI): {{ page.rdf }}, rdfs:label: {{ page.rdf | rdf_property: '<http://www.w3.org/2000/01/rdf-schema#label>' }}</br>
    Content:
    {{ content }}

a file `hallo/index.md`:

    ---
    layout: "default"
    ---
    
    This is index in Hallo

a graph:

```
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.org/> .

ex: a foaf:Document ;
    rdfs:label "This is the base page" .

<http://example.org/hallo/> a foaf:Document .

ex:project a foaf:Document ;
    rdfs:label "Projects" .
```

`_config.yml`

```
# Site settings
url: http://example.org/
baseurl: ""

# Build settings
markdown: kramdown

# jekyll-rdf
plugins:
    - jekyll-rdf
jekyll_rdf:
    path: "rdf-data/content.ttl"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Document" : "document.html"
```

Depending on the order of the pages in the classmap the pages are replicating the content of the previous page additionally the content of `hallo/index.md` is also rendered to all pages:

    classMapped: http://xmlns.com/foaf/0.1/Document : http://example.org/ : document.html 
    classMapped: http://xmlns.com/foaf/0.1/Document : http://example.org/hallo/ : document.html 
    classMapped: http://xmlns.com/foaf/0.1/Document : http://example.org/project : document.html 

`http://example.org/project/`:

```
    PageRDF (this URI): http://example.org/project
    rdfs:label: Projects

Content:

    PageRDF (this URI): http://example.org/hallo/
    rdfs:label:

Content:

    PageRDF (this URI): http://example.org/
    rdfs:label: This is the base page

Content:

This is index in Hallo
```

Expected is:

```
    PageRDF (this URI): http://example.org/
    rdfs:label: This is the base page

Content:
```

```
    PageRDF (this URI): http://example.org/hallo/
    rdfs:label: 

Content:

This is index in Hallo
```

and

```
    PageRDF (this URI): http://example.org/project
    rdfs:label: Projects

Content:

```
